### ISSUE TITLE
Subtitles from previous episode re-played when playing next episode

### ISSUE THREAD

**Issue by MarcHulsebosch** [jellyfin/jellyfin-androidtv#108]
On Android TV, watching multiple episodes of a TV series in a row, and either waiting for the next episode to begin or clicking the button on the "Up Next" screen, the next episode to play will re-play the subtitles from the previous episode. Video and Audio stream are correct for the new episode.

**Comment by thornbill** [comment]
I'm not sure what happened to the original content of this issue, but I have restored it from my email.

I have also noticed this issue with subtitles not matching the current episode.

**Comment by K900** [comment]
Can confirm this is still an issue on the latest Play Store release.

**Comment by tayhr** [comment]
> Can confirm this is still an issue on the latest Play Store release.

It's still happenning here.

**Comment by Artiume** [comment]
@thornbill you know if this'll be addressed with the UX update or is it a deeper issue?

**Comment by tayhr** [comment]
> @thornbill you know if this'll be addressed with the UX update or is it a deeper issue?

If it helps you, i'm having the same problem with jellyfin web for windows.

**Comment by Artiume** [comment]
Then it's probably a backend issue. jellyfin-web and androidtv don't really share code. @tayhr could you make a report on the main repo with your info, it could help us pinpoint the issue.

**Comment by tayhr** [comment]
@Artiume done.

**Comment by nielsvanvelzen** [comment]
> @thornbill you know if this'll be addressed with the UX update or is it a deeper issue?

We did make some changes in the "play next" functionality but I suspect this issue won't be fixed by those. I can't reproduce this either when binge watching something.

**Comment by tayhr** [comment]
@nielsvanvelzen there's something that I can help with this? Unfortunately it doesn't show anything in the log

**Comment by nielsvanvelzen** [comment]
Can you give some additional information about what kind of subtitles are playing and what your preferences are in the web client under the "subtitles" tab?

**Comment by tayhr** [comment]
my config:
> Preferred subtitle language: Any Language
> Subtitle mode: Default
> Burn subtitles: Auto
> Text size: Normal
> Font: Default
> Drop shadow: Drop shadow

video config:
Subtitle in use: external .srt
![image](https://user-images.githubusercontent.com/18019271/78823377-f5035f80-79b2-11ea-9946-97a93f925f5d.png)
![image](https://user-images.githubusercontent.com/18019271/78823552-457abd00-79b3-11ea-8d69-fc0d0d3cfad2.png)

**Comment by billyinferno** [comment]
I got the same problem on last build on jellyfin web (using windows, firefox) this is usually happen when I skipping while playing (like keep pressing right arrow button) and when the next episode play it still showed the previous subtitle.

What I need to do just stop, then go back, refresh, then re-open the episode then it will work.

My suspect as far as I remember when I got this case and check is, as SRT being send dynamically in json format to web client, it seems when the next video played it still opening the cache json of the previous subtitle instead extract and create the new subtitle for that episode. I am not bother enough about this, as I can just stop, refresh, and play it again, so didn’t have chance to get and check the log.

If found again, I’ll try to give more information with log.

**Comment by ManuLinares** [comment]
> On Android TV, watching multiple episodes of a TV series in a row, and either waiting for the next episode to begin or clicking the button on the "Up Next" screen, the next episode to play will re-play the subtitles from the previous episode. Video and Audio stream are correct for the new episode.

I have the same bug, It's super annoying choosing subtitles every time a video ends...

**Comment by oBusk** [comment]
I still have this issue, android tv app version 0.11.5 and server version 10.7.5 (Linux x64)

**Comment by sabas** [comment]
Server version Jellyfin.Server 10.7.6.0 and app from the store.
I have mkvs with embedded subtitles grouped in a season. When one ends the button to start the next one appear on tv, I click on it and the next episode starts with the same subtitle.
I pause, go back on the CC menu and the option "None" is selected. So I go to the "English" subtitle and re-loads it correctly.
