### ISSUE TITLE
Switch audio with stacked versions

### ISSUE THREAD

**Issue by kjvalencik** [jellyfin/jellyfin-androidtv#3264]
### Describe the bug

I have two versions of a video using stacked naming. They are correctly showing as a single title with multiple versions.

1. Title - Version A.mkv. Multiple audio tracks.
2. Title - Version B.mkv. Single audio tracks.

When playing Version A, I do not get the option to switch audio tracks. If I "unstack" the files and play Version A, I **do** get the option to switch tracks.

In the stacked version, both videos play successfully, but Version A doesn't use the default audio tracks. Instead, it switches to a track that matches the codec of Version B.

I have a feeling that this is something not working quite right with stacked files when they don't have identical audio tracks.

I have a bit of Android development experience and would be happy to debug further and contribute a fix if you could kindly point me in the area of the code I should look.

Cheers!

### Application version

0.16.2

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon Fire Stick 4k Max

### Android version

Fire OS 8.3.2.1

### Jellyfin server version

10.8.13

**Comment by MichaelRUSF** [comment]
It sounds like only version B is playing when you have the files stacked, even when you select version A to play. The version selector #3183 is somewhat broken in the JellyfinATV client using the current 10.8.z server build, but should be fixed in the 10.9 build.

**Comment by mikewesten** [comment]
Highest to lowest resolution WIDTH determines the order. If version A is something like 1916x1080p and version B is 1920x1080p, then version B will be played always, even if you select version A. Jellyfin's version stacking uses logic that works in contradiction to alphabetical naming. The original coders clearly had something else in mind when they wrote this. Something more like a standard streaming platforms descending quality options, where bandwidth and hardware determines delivery of HD versus SD options, etc.

**Comment by kjvalencik** [comment]
The files have two different lengths. I'll need to double check, but I think it's correct playing the correct version when selected.

@mikewesten, the version with multiple audio files is _also_ the larger resolution (Version A is `3840x2160` and Version B is `3840x1608`). With those rules, shouldn't I still see the audio selector?

**Comment by mikewesten** [comment]
In that case then I don't know. Just trying to rule out the possibility that it's a version selection issue.

**Comment by kjvalencik** [comment]
I'll try out the 10.9 build and report back. Thanks for the tip!

**Comment by kjvalencik** [comment]
Taking a closer look, even though the runtime _looks_ like it's Version A, it's actually Version B and will stop playing at the runtime of Version B (before Version A should end). This explains why there's no audio track selection.

Unfortunately, Jellyfish 10.9 does **not** fix the issue. It continues to always play Version B.

**Comment by kjvalencik** [comment]
Closing as a duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/3183.

**Comment by MichaelRUSF** [comment]
Try renaming the files using this naming scheme:
Title - Version A 2160p.mkv
Title - Version B 1608p.mkv

**Comment by kjvalencik** [comment]
@MichaelRUSF Woah! That naming worked.

The file naming needing to be this specific feels like a bug. Possibly lists getting sorted in two different ways? When I get a chance, I'll hook up a debugger and see if I can figure it out.
