### ISSUE TITLE
Chinese subtitles cannot be displayed correctly in LibVLC player

### ISSUE THREAD

**Issue by Strangevy** [jellyfin/jellyfin-androidtv#3693]
### Describe the bug

Alternate fonts have been configured, and they are effective on the web side, which can display Chinese correctly, but they are not effective when playing with LibVLC on the TV side.

The integrated player on the Android phone side is also the same garbled performance, so it is no problem to use the web player.
![1719028468921_d](https://github.com/jellyfin/jellyfin-androidtv/assets/7418194/1ee8e016-9f28-4b5b-8a9f-427e742b1912)

### Application version

0.16.11

### Device information

xiaomi tv s pro 85

### Android version

hyper os 1.0.21.0

### Jellyfin server version

10.9.6

**Comment by TheLonelinessOfHS** [comment]
This developer is going to blame the backend configuration and refuse to fix this, whilst the Android TV app is actually the only one that doesn't work, aside from android and web.

**Comment by Strangevy** [comment]
This problem has been solved. Refer to this [article](https://sspai.com/post/67764) for more details.

**Comment by Geeksun2018** [comment]
I also have this issue. I also set an alternative font, but it didn't work

**Comment by TheLonelinessOfHS** [comment]
> I also have this issue. I also set an alternative font, but it didn't work

Same here. It wouldn't. It worked in some previous versions but got broken.

**Comment by Strangevy** [comment]
> > I also have this issue. I also set an alternative font, but it didn't work
> 
> Same here. It wouldn't. It worked in some previous versions but got broken.

In addition to setting up alternate fonts, you need to install fonts in the container:
```
apt update
apt install fonts-noto-cjk-extra
```
@TheLonelinessOfHS @Geeksun2018

**Comment by TheLonelinessOfHS** [comment]
> > > I also have this issue. I also set an alternative font, but it didn't work
> > 
> > 
> > Same here. It wouldn't. It worked in some previous versions but got broken.
> 
> In addition to setting up alternate fonts, you need to install fonts in the container:
> 
> ```
> apt update
> apt install fonts-noto-cjk-extra
> ```
> 
> @TheLonelinessOfHS @Geeksun2018

That still doesn't explain why the Android app works well but the TV version doesn't.

**Comment by thornbill** [comment]
> That still doesn't explain why the Android app works well whilst the TV version doesn't

They are different apps with different capabilities.

**Comment by TheLonelinessOfHS** [comment]
> > That still doesn't explain why the Android app works well whilst the TV version doesn't
> 
> They are different apps with different capabilities.

Then why they are all called Jellyfin? To me this is more like an excuse, emphasising their differences while skipping over their consistency in core functions like subtitles.

**Comment by nielsvanvelzen** [comment]
This should no longer be an issue in 0.17.

**Comment by TheLonelinessOfHS** [comment]
I can confirm that the issue has been resolved in the latest beta. Thanks for your efforts.

**Comment by TheLonelinessOfHS** [comment]
> This should no longer be an issue in 0.17.

For some reasons the same issue occurred again in the latest release.

**Comment by nielsvanvelzen** [comment]
Not possible because there no longer is a LibVLC implementation in 0.17. Closing as resolved.
