### ISSUE TITLE
Selecting embedded subtitle track leads to different track being displayed

### ISSUE THREAD

**Issue by 854562** [jellyfin/jellyfin-androidtv#4183]
### Describe the bug

1. Play a video with embedded subtitles
2. Select subtitle track `x`
3. Observe subtitle track `x+2` being displayed

This only happens with embedded subtitles, both SRT and PGS. Selecting an external SRT subtitle will correctly display the selected track.

Note: I am using the Subtitle Extract plugin.

### Logs

Logs don't show much besides some SRT parsing errors (not sure if this is relevant to this bug or just a coincidence):

`[ERR] [25] MediaBrowser.MediaEncoding.Subtitles.SubtitleEditParser: 130 errors encountered while parsing '"srt"' subtitle using the "SubRip" format parser, errors: "Line 17: Empty line expected, but found number (1) followed by time code.
Line 36 - error reading time code: 3
Line 64: Empty line expected, but found number (5) followed by time code.`
etc.

### Application version

0.18.0-beta.2

### Device information

Chromecast with Google TV (4K)

### Android version

Android 12

### Jellyfin server version

10.10.1

**Comment by Hello-World-Traveler** [comment]
Could fix? https://github.com/jellyfin/jellyfin-androidtv/pull/4154

**Comment by nielsvanvelzen** [comment]
Is the video transcoding when this issue happens or does it also happen when direct playing?

**Comment by MichaelRUSF** [comment]
I did some testing I have a clearer picture of what’s happening. The index is off for embedded subtitles by the amount of external subs that you have. Selecting External tracks will always work with the correct index.  When you select the embedded track the index is going to be x + (number for external tracks). 

Example 1:
Movie.mkv  (two embedded tracks one external) 
Embedded English PGS (Internal track 1)
Embedded English SDH PGS  (Internal  track 2)
External English SRT (External track 1)

So example 1 since I have one external track and select Internal track 1 will actually play Internal track 2.  If I select Internal track 2  it wraps around and will play External track 1

In  example 2 the index will be off by two since there 2 since there are two eternal tracks. 
Example 2:
Movie.mkv  (\two embedded tracks two external) 
Embedded English PGS (Internal track 1)
Embedded English SDH PGS (Internal  track 2)
External English SRT (External track 1)
External English SDH SRT (External track 2)

In this case since I have two external track and select the Internal track 1 will play External English SRT (External track 1) since the index if off my 2 now and it wraps around.

Also worth nothing that when test External PGS don’t display anything, so If you have them the same behavior is observed you just won’t see anything.

**Comment by 854562** [comment]
@MichaelRUSF Thank you for being so thorough in your testing. I hadn't considered the (number of) external subtitles could've caused it. I can confirm that the issue does not occur when the external .srt files are removed from the movie folder.

To answer @nielsvanvelzen's question: the issue only occurs when direct playing. When forcing a transcode by lowering the max bitrate, the correct subtitle track is loaded, regardless of available external subtitles. I could only test this with SRT subtitles, since PGS subs do not appear at all for me when transcoding (possbily running into #4182).

**Comment by MichaelRUSF** [comment]
That PR didn't fix the issue. Now when select the embedded tracks it just goes back to "None" as the selection. 

Here is a sample [file](https://www.mediafire.com/file/gw11prj4nrxpovz/Sintel_%25282010%2529.zip/file) with custom subtitles that should help you recreate the issue.

**Comment by nielsvanvelzen** [comment]
#4201 should fix the issue, thanks for providing the test files @MichaelRUSF that definitely helped reproduce the issue.

**Comment by MichaelRUSF** [comment]
This resolves the issue for me, also mentioned as the second issue in this [comment](https://github.com/jellyfin/jellyfin-androidtv/pull/4094#issuecomment-2425131644).  Subtitles work great now. 

Just one issue remains. External PGS doesn't display anything when loaded. I normally don't have external PGS files but I extracted them to test out since the server added support for streaming PGS subtitles without transcoding for external .sub / .sup files. I can document this as a new issue if it's supposed to work.

**Comment by nielsvanvelzen** [comment]
I can reproduce the issue with external PGS, it looks like the video player correctly loads and parses the subtitles so why nothing is showing is a mystery to me. Unless I can figure this out I'll probably disable external pgs for now.
