### ISSUE TITLE
Subtitles are always on, for every video

### ISSUE THREAD

**Issue by basildane** [jellyfin/jellyfin-androidtv#4383]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

1. Play any movie
2. Subtitles are displayed

What should happen:
Subtitles should only be displayed if I request subtitles.

If I turn off subtitles, they will be back on the next time I play a movie.
I have to disable subtitles EVERY SINGLE TIME I click play on ANYTHING.

Note:
I spent an hour going through every setting on the JellyFin server, the user account profile, the player settings on the Shield device, and the settings on the Shield itself.
The only setting I could find was in the Shield, which was in Devices / Accessibility / Captions.   It is already set to OFF.

### Application version

0.18.3

### Where did you install the app from?

Google Play Store

### Device information

Nvidia Shield

### Android version

Unknown

### Jellyfin server version

10.10.3

**Comment by nylimited** [comment]
I have experienced various issues with subtitles and found some "interesting" things ..  

Firstly, a lot of (downloaded) movies have their first subtitle track flagged as "default track" which should probably trigger the automatic display of that track. 

I also noted several problems with subtitles presented in SSA or ASS format where clients, such as AndroidTV and the Roku client simply failed to show them, even when manually turned on.  This is not the case when using the Jellyfin web client.

My simple answer is to recreate all containers (mkv, mp4 etc) using ffmpeg and force the default subtitle track flag to "no" on all subtitle tracks and, at the same time, convert all subtitles to SRT format. 

Any subtitle that should be forced (also often flagged incorrectly) needs to be reinstated manually using my method.  Rewriting all media containers as described solved ALL my subtitle issues.

**Comment by basildane** [comment]
@nylimited Thank you for your incite.  I just checked and you are correct that it is related to the "default" attribute.  (ffprobe)
For example, I just picked a random movie and it started showing Dutch subtitles.

A few points.
This is ONLY an issue in the Jellyfin android app.  No other programs do this, including the Jellyfin web player.  Even Plex turned off subtitles if I said turn off subtitles.  But this app turns it back on and does not remember my settings.  If I tell it no subtitles, it means no subtitles.  The app keeps turning subtitles back on, and that's a bug.

Second point, I agree with you that manually changing all my thousands of videos could be a work around, but damn, that's going to be a huge effort.  It also means writing to my video library, which has some risks of corruption.  I suppose I could write something that would go through all my libraries and change all my precious videos, but I'm hesitant to do that.

**Comment by nylimited** [comment]
Absolutely correct, @basildane !  While I am using ffmpeg to rewrite all my *new* media I do not have enough computer time or CPU cycles I can dedicate to a full library cleanup.  I was originally testing with the Jellyfin web client and none of these issues are visible there.  The only setting that should automatically trigger the display of a subtitle track is the "Forced" flag set to on according to my limited understanding. As an example, this is needed in the movie "CODA" to automatically display English subtitles when actors are using ASL (which most of us do not know).

The automatic display does seem to be an AndroidTV (perhaps Roku as well - I need to test more one day) problem. The other issues involving SSA and ASS subtitles is different and I have seen Plex mishandle some of those also.

I am not aware of software that can flip the settings without creating a completely new container so, yes, if we were to attempt changing an entire library we'd setting up a 'torture test' for the disk drives.  ;)

**Comment by basildane** [comment]
Tested on Samsung phone with Jellyfin app from play store.  Same problem.

**Comment by BotBlake** [comment]
Hi @basildane
Could it be that Jellyfin is configured to automatically select tracks marked as default?
Since this is not a client-specific setting, it could explain why you’re experiencing this issue across all your clients.

You can check and adjust the subtitle settings in Jellyfin Web by navigating to:
User → Subtitles

Under "Subtitles," you’ll find the "Subtitle mode" option, along with explanations for the different modes.

There is an issue with some of the selection modes, which has already been reported here: jellyfin/jellyfin/issues/10829. This is a server-side problem, as the default settings are applied and stored there.

For now, setting the subtitle mode to "None" should resolve the issue. (by fully disabling subtitles by default)


If this does NOT solve your problem, please let us know so we can investigate further.

Kind regards

**Comment by gizmomelb** [comment]
0.18.6 android tv client tested on google chromecast as well as miibox android media player.

Changing the size of the subtitles in the android app is not respected with the next media played.

1. Changing subtitle size to 25% in the android app would always have the subtitles back at 100% when the next episode / movie is played.

Enhancement request / bug - the android app should allow the account to choose language AND to enable / disable subtitle choices from the app, not just the web interface please.

**Comment by BotBlake** [comment]
@gizmomelb First of all, if you believe you have found a new issue, please create a new one and dont comment on closed, non-related ones. Additionaly please never sum up multiple issues into one issue report.

Also the AndroidApp does allow changing language and subtitles once in the player!
Open the seek menue during a movie and note how there are settings for "subtitles" and "audio".

Kind regards

**Comment by whoo** [comment]
Hi,

It also happens in the web player. 
Disabling and enabling... multiplies the same subtitle. :)
The subtitle is "SRT" in MKV format.

* Version du serveur 10.10.7
* Version web 10.10.7
* Version du build 10.10.7

<img width="769" height="329" alt="Image" src="https://github.com/user-attachments/assets/91635b63-1147-48f9-8508-9794d4097fd6" />
<img width="857" height="408" alt="Image" src="https://github.com/user-attachments/assets/4204fe4d-e5e7-4df4-ad7f-8d031cffc804" />

**Comment by stephenreay** [comment]
> For now, setting the subtitle mode to "None" should resolve the issue. (by fully disabling subtitles by default)
> 
> If this does NOT solve your problem, please let us know so we can investigate further.
> 
> Kind regards

I've just tried this (in the web client), and indeed it did not fix the issue.

The crazy part is if I open a video it *says* subtitles are off in the playback menu... while showing the subtitles on the video.

**Comment by oss-graphg** [comment]
> I've just tried this (in the web client), and indeed it did not fix the issue.
>
>The crazy part is if I open a video it says subtitles are off in the playback menu... while showing the subtitles on the video.

I have the same problem while on LgTV playing Jellyfin from Web browser… it’s kind of annoying. But I think I’ll just remove all subtitles using MlvToolnix from my videos cause no one is watching them with subtitles 😢

**Comment by EMP83** [comment]
Same problem for me. Server 10.11.5 and client jellyfin android app on google tv.

**Comment by cybertlc** [comment]
Same problem on 10.11.5 . Subtitles set to NONE still show subtitles. NONE means NONE, but this isn't working. A bug.

**Comment by davet2001** [comment]
I have the same issue, with a workaround.

Every video (played in Jellyfin Roku), has subtitles turned off, but they are still showing.

Workaround:
Set subtitles to on
Set subtitles to off

Now they are actually off.

It is extremely annoying that the first part of playback of *literally every video* I have to do this dance to turn off subtitles. But it does work.

**Comment by bilbofroggins** [comment]
Why was this closed @BotBlake ? I'm also having issues even when changing the caption setting to None. I have to do @davet2001 's workaround - turn it on then back off, for every video that loads :(

**Comment by BotBlake** [comment]
Okay. I have no Ideas how you guys keep finding this issue.
This here is the Jellyfin-AndroidTV repository.

This issue is NOT within the Jellyfin AndroidTV Client though!
You guys have now commented that this issue also is happening on `Jellyfin Android`, `Jellyfin Roku`, `Jellyfin Web` and even `Jellyfin WebOS`. This is because the default audio- and subtitle tracks are chosen by the Jellyfin-Server (Based on User preference), not the Client.

Last year I have already linked to THIS possibly related server-issue https://github.com/jellyfin/jellyfin/issues/10829
If you dont think that issue describes the problem well enough, open a new one on the server repository and link it here for others to find!

Kind regards

**Comment by cybertlc** [comment]
Here's the interesting thing.  It happens on my TCL Smart TV, but not on my GoogleTV Onn Pro in another room. Same software, same settings, same account, same everything.  Is this an issue specific to a certain Android build?  I can reproduce it right now on my end on the TCL TV.  Subs are set to OFF, but it will play it for ANY AND EVERY movie streamed that has subtitles. Set to OFF, yet it plays it for every movie/episode and I have to turn it off individually each time I hit play.

**Comment by davet2001** [comment]
@BotBlake There is definitely a problem with the Roku client.

On the client it says:
**Subtitles OFF**
But the subtitles still show.


They only stop showing if I turn them on then off.
So the client interface in the first instance has an error because it's displaying a setting that is not true.

**Comment by BotBlake** [comment]
@davet2001 It is possible that the Jellyfin server sends a subtitle stream (that the client will display) but doesnt tell the client which of the available Subtitle streams it is. The client therefore knows its displaying a subtitle Stream but not which one.

So this CAN still be exclusively caused by a server-side issue
Also.... Its possible that this is related to a separate issue on jellyfin-roku, I dont know and have not questioned that.
Its NOT an issue on Jellyfin-AndroidTV though, which is why this issue was closed.

**Comment by bilbofroggins** [comment]
👍 Thanks for the clarification and linked ticket, that makes sense

**Comment by davet2001** [comment]
> @davet2001 It is possible that the Jellyfin server sends a subtitle stream (that the client will display) but doesnt tell the client which of the available Subtitle streams it is.

Sure. But that's still a bug in the Roku client IMO:

1. Server sends a subtitle stream not burned into the video.
2. Client displays that subtitle stream.
3. Client UI shows that subtitles are off.

The problem is that 2 & 3 are happening together. It should not be possible for the UI to show that subtitles are off, and for it also to be rendering subtitles. But exactly that happens, on every video. You can literally see 'off' and the text at the same time.

The on/off workaround seems to nudge the UI back into reality.

**Comment by BotBlake** [comment]
@davet2001 There might be an issue on the Jellyfin-Roku Client.
I dont know that nor can I verify it.
This is the repository for the official **AndroidTV** App though. If you believe you have found a bug in Jellyfins App for Roku, you will have to report it there. https://github.com/jellyfin/jellyfin-roku
Kind regards

**Comment by bestlem** [comment]
Iy is on the Jellyfin iOS client as well

**Comment by Atomosic** [comment]
This issue is occurring for me as well on IOS, even toggling subtitles leaves it on screen unfortunately .
