### ISSUE TITLE
Switched channels with Opus audio

### ISSUE THREAD

**Issue by neon-dev** [jellyfin/jellyfin-androidtv#4435]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-androidtv/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Describe the bug

I've noticed a problem with the app on my Fire TV stick where the center channel plays from the right with 5.1/7.1 Opus audio streams. This was previously fixed in #3203, but the fix doesn't work anymore. I couldn't find a recent issue about this, but what I found instead was this [forum post](https://forum.jellyfin.org/t-audio-routing-issue-with-opus-5-1-or-7-1-content?pid=43150#pid43150):

> [theguymadmax](https://forum.jellyfin.org/u-theguymadmax) 2024-11-19, 02:42 AM:
> 
> This [commit](https://github.com/androidx/media/commit/b1541b096f9dc4d1f9ca71b6743c836f6bd4de89) resolves the issue in ExoPlayer(Androidx Media3) version 1.21 and later. It was considered fixed when the ATV client [upgraded](https://github.com/jellyfin/jellyfin-androidtv/issues/3203) to ExoPlayer version 1.21. Currently, the ATV client is using version 1.4.1.
> 
> I did some testing, and it seems that the fix is no longer needed, and actually causes the issue now. Correct channel mapping works with earlier versions of ExoPlayer that don't include this patch. For example, if you use [Just Player](https://github.com/moneytoo/Player/releases/tag/v0.154) version .154, which is based on ExoPlayer 1.20, you'll see that the channels are mapped correctly.

### Media info of the file

```shell

```

### FFmpeg logs

```shell

```

### Application version

0.18.4

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Stick 4K (2nd Gen)

### Android version

Fire OS 8.1.2.5

### Jellyfin server version

10.10.5

**Comment by channeladam** [comment]
I came across this issue when I changed from the Gen 1 to the Gen 2 - the audio channel issue is only on the Gen 2 not the Gen 1.  https://github.com/jellyfin/jellyfin-androidtv/issues/4258#issuecomment-2888965474

I posted about this here on the Amazon forum - https://www.amazonforum.com/s/question/0D5Kf00003WwyL8KAJ/fire-tv-stick-4k-max-gen-2-broke-opus-51-and-71-audio-channel-mapping?t=1748094861548

And I have eventually made my way with an official support ticket through to where a technical customer service person from Amazon says they are looking into it and will get back to me in a few days...

**Comment by neon-dev** [comment]
I've now found https://github.com/androidx/media/issues/1902, which also states that it's a device specific problem.
No idea whether this should be fixed in the media lib or in Fire OS. Based on the discussions so far, it seems unlikely to happen in either place and I'm not sure if the Jellyfin team could even help here :confused:

**Comment by JimmyHoke** [comment]
I can confirm this on my FireTV 4K Max Gen 2. Any opus 5.1 channel audio has the channel order mixed up. Playing through Kodi works perfectly.

**Comment by channeladam** [comment]
After a lengthy back-and-forward conversation (14 emails over a month) with Amazon Tech Support Executive Customer Relations, their conclusion to their investigation was this:

```
Our technical team has completed comprehensive testing using Google's ExoPlayer (the industry's benchmark testing application) which correctly handles both Opus 7.1 and Opus 5.1 audio channel mapping.

Our investigation indicates that this is an external issue specific to the Jellyfin app. An important factor to consider is the different Android versions used in FireTV devices:

- FireTV Gen1: Android 9
- FireTV Gen2: Android 11

The Jellyfin app may use different APIs depending on the Android version, which is an app-side implementation beyond our control.

Given these findings, we recommend:

1. Kindly use Google's ExoPlayer as an alternative for testing and verification
2. Kindly contact Jellyfin's support team directly to address the app-specific issue.

We understand this might not be the solution you were hoping for, but we want to be transparent about our findings and provide you with the most effective path to resolution.
```

So they think Jellyfin is to blame for the issue on the Gen2 with Android 11.

Can anyone from the Jellyfin team shed any further light on this, or does it trigger a thought?
@nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
There is a "Prefer FFmpeg for audio playback" option in the developer option section of the app. Try enabling that and see if that solves the issue.

**Comment by JimmyHoke** [comment]
> There is a "Prefer FFmpeg for audio playback" option in the developer option section of the app. Try enabling that and see if that solves the issue.

This didn't fix it for me. Also, I tried the "downmix to stereo" and it caused video to transcode as well so that isn't effective at fixing the issue.

**Comment by channeladam** [comment]
> There is a "Prefer FFmpeg for audio playback" option in the developer option section of the app. Try enabling that and see if that solves the issue.

This didn't cause any difference.

**Comment by nielsvanvelzen** [comment]
Ok thanks for testing. If you use a different video player on your device (like the VLC app) with the same file, does that work?

**Comment by channeladam** [comment]
> Ok thanks for testing. If you use a different video player on your device (like the VLC app) with the same file, does that work?

Playing via Kodi works perfectly.
Playing via Nova Player works perfectly.
Playing via VLC... the front, right and center channels are correct, but it doesn't play the subwoofer or back channels.

**Comment by JimmyHoke** [comment]
> > Ok thanks for testing. If you use a different video player on your device (like the VLC app) with the same file, does that work?
> 
> Playing via Kodi works perfectly.
> Playing via Nova Player works perfectly.
> Playing via VLC... the front, right and center channels are correct, but it doesn't play the subwoofer or back channels.

Can also confirm that Kodi works perfectly.

**Comment by neon-dev** [comment]
> please comment confirming if this issue still affects you in the latest release or master branch

I no longer own a Fire TV stick, so someone else will have to confirm.

**Comment by apurohit8** [comment]
I'm late to the party (been on Roku Jellyfin)... getting into Fire Stick JF now, and I have a Gen2 and can confirm the issue still persists. Center channel audio coming from right speaker...

I'm happy to repeat testing and help out any way I can... let me know what you need.

**Comment by channeladam** [comment]
Still a problem with the latest version.
